x-restart: &default-restart
  restart: unless-stopped

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    <<: *default-restart
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    <<: *default-restart
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    <<: *default-restart
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio
    <<: *default-restart
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # --- Notificaciones AMQP (slot 1) ---
      MINIO_NOTIFY_AMQP_ENABLE_1: "on"
      MINIO_NOTIFY_AMQP_URL_1: ${RABBITMQ_URL}
      MINIO_NOTIFY_AMQP_EXCHANGE_1: ${AMQP_EXCHANGE}
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_1: "direct"
      MINIO_NOTIFY_AMQP_ROUTING_KEY_1: ${AMQP_ROUTING_KEY}
      MINIO_NOTIFY_AMQP_DURABLE_1: "on"
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    volumes:
      - minio_data:/data

  # Init MinIO: create uploads and vod buckets
  minio-mc:
    image: minio/mc:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio-mc
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_UPLOADS: ${S3_BUCKET_UPLOADS}
      S3_BUCKET_VOD: ${S3_BUCKET_VOD}
    entrypoint:
      - /bin/bash
      - -lc
      - |
        set -euo pipefail
        echo "Waiting for MinIO..."
        until mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" >/dev/null 2>&1; do
          sleep 2
        done
        mc mb -p "local/${S3_BUCKET_UPLOADS}" || echo "Bucket ${S3_BUCKET_UPLOADS} already exists"
        mc mb -p "local/${S3_BUCKET_VOD}"     || echo "Bucket ${S3_BUCKET_VOD} already exists"
        echo "Current Buckets:"; mc ls local || true
    restart: "no"

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: ${COMPOSE_PROJECT_NAME}-meilisearch
    <<: *default-restart
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
  
  minio-amqp:
    image: minio/mc:latest
    container_name: ${COMPOSE_PROJECT_NAME}-minio-amqp
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      MC_TTY: "0"
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_UPLOADS: ${S3_BUCKET_UPLOADS}
      MINIO_NOTIFY_AMQP_SLOT: ${MINIO_NOTIFY_AMQP_SLOT}
      AMQP_URL: ${RABBITMQ_URL}
      AMQP_EXCHANGE: ${AMQP_EXCHANGE}
      AMQP_ROUTING_KEY: ${AMQP_ROUTING_KEY}
      MINIO_EVENT_PREFIX: ${MINIO_EVENT_PREFIX}
      MINIO_EVENT_SUFFIX: ${MINIO_EVENT_SUFFIX}
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -euo pipefail
        echo "Esperando MinIO..."
        until (/usr/bin/mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" >/dev/null 2>&1); do sleep 2; done

        echo "Agregando regla de eventos en bucket $S3_BUCKET_UPLOADS (AMQP slot $MINIO_NOTIFY_AMQP_SLOT ya definido por env en MinIO)"
        /usr/bin/mc event add local/$S3_BUCKET_UPLOADS \
          arn:minio:sqs::${MINIO_NOTIFY_AMQP_SLOT}:amqp \
          --event put \
          ${MINIO_EVENT_PREFIX:+--prefix "$MINIO_EVENT_PREFIX"} \
          ${MINIO_EVENT_SUFFIX:+--suffix "$MINIO_EVENT_SUFFIX"} || true

        echo "Reglas actuales:"
        /usr/bin/mc event list local/$S3_BUCKET_UPLOADS || true
        echo "Listo."
    restart: "no"
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: ${COMPOSE_PROJECT_NAME}-clickhouse
    <<: *default-restart
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123" # HTTP interface
      # - "9000:9000" # Native protocol (optional)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    <<: *default-restart
    depends_on:
      postgres:
        condition: service_healthy
      prisma-init:
        condition: service_completed_successfully
    environment:
      PORT: ${BACKEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      S3_ENDPOINT: ${MINIO_S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      S3_FORCE_PATH_STYLE: "true"
      S3_BUCKET_UPLOADS: ${S3_BUCKET_UPLOADS}
      S3_BUCKET_VOD: ${S3_BUCKET_VOD}
      MEILI_HOST: ${MEILI_HOST}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${BACKEND_PORT}:3000"

  # One-time Prisma schema push to create tables from schema.prisma
  prisma-init:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-prisma-init
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # OpenSSL engine env mirrors backend to ensure Prisma engines run
      PRISMA_ENGINE_OPENSSL_VERSION: 3.0.x
    entrypoint:
      - /bin/sh
      - -lc
      - |
        set -euo pipefail
        echo "[prisma-init] Starting schema push..."
        echo "[prisma-init] PWD=$(pwd)"
        echo "[prisma-init] DATABASE_URL=$DATABASE_URL"
        echo "[prisma-init] Listing /app and /app/prisma"
        ls -la /app || true
        ls -la /app/prisma || true
        echo "[prisma-init] Prisma CLI version:"
        npx prisma -v || ./node_modules/.bin/prisma -v || true
        if [ ! -f /app/prisma/schema.prisma ]; then
          echo "[prisma-init] ERROR: /app/prisma/schema.prisma not found" >&2
          exit 1
        fi
        echo "[prisma-init] Running prisma db push..."
        npx prisma db push --schema=/app/prisma/schema.prisma --accept-data-loss --skip-generate || \
        ./node_modules/.bin/prisma db push --schema=/app/prisma/schema.prisma --accept-data-loss --skip-generate
        echo "[prisma-init] Done: Prisma schema applied successfully."
    restart: "no"

  nginx:
    image: nginx:1.25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    <<: *default-restart
    depends_on:
      - backend
      - minio
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - hls_renditions:/var/www/hls:ro

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  minio_data:
  meili_data:
  clickhouse_data:
  hls_renditions:
